import { DataQualityService } from '../server/services/DataQualityService';
import { UnifiedDataLayer } from '../server/import/UnifiedDataLayer';
import { ConnectionManager } from '../server/database/ConnectionManager';

export async function runDataQualityTests(): Promise<{ name: string; passed: boolean; error?: string }[]> {
  const results: { name: string; passed: boolean; error?: string }[] = [];

  function assert(name: string, condition: boolean, message?: string) {
    if (condition) {
      results.push({ name, passed: true });
    } else {
      results.push({ name, passed: false, error: message || 'Assertion failed' });
    }
  }

  // Set up dummy session & Unified Data Layer
  const sessionId = 'dq_test_session_1';
  const uds = UnifiedDataLayer.getInstance();
  
  // Create an imported dataset with mixed quality data
  const testData = [
    { id: 1, name: 'Alice', score: 95, registered: '2023-01-01', status: 'active' },
    { id: 2, name: 'Bob', score: 85, registered: '2023-02-15', status: 'inactive' },
    { id: 3, name: '', score: null, registered: 'invalid-date', status: 'active' },
    { id: 4, name: '   ', score: 1000, registered: '2050-01-01', status: 'unknown' },
    { id: 2, name: 'Bob', score: 85, registered: '2023-02-15', status: 'inactive' }, // Duplicate row
    { id: 'not-an-int' as any, name: 'Charlie', score: -10, registered: '2023-03-10', status: 'active' } // Type inconsistency on id
  ];

  const columns = [
    { name: 'id', dataType: 'integer', isNullable: false, nullCount: 0, sampleValues: [] },
    { name: 'name', dataType: 'text', isNullable: true, nullCount: 0, sampleValues: [] },
    { name: 'score', dataType: 'numeric', isNullable: true, nullCount: 0, sampleValues: [] },
    { name: 'registered', dataType: 'date', isNullable: true, nullCount: 0, sampleValues: [] },
    { name: 'status', dataType: 'text', isNullable: true, nullCount: 0, sampleValues: [] }
  ];

  await uds.registerDataset(
    sessionId,
    {
      sourceName: 'test.csv',
      fileType: 'CSV',
      columns: columns as any,
      rows: testData
    }
  );

  // The dataset name generated by UnifiedDataLayer will be sanitized from 'test.csv' -> 'test'
  try {
    const profile = await DataQualityService.profile(sessionId, 'imported', 'test', true);

    assert('1.1 Data Quality Score is calculated between 0 and 100', profile.overallQualityScore! >= 0 && profile.overallQualityScore! <= 100);
    assert('1.2 Quality Score Category exists', ['Excellent', 'Good', 'Fair', 'Poor'].includes(profile.qualityScoreCategory!));
    assert('1.3 Correct total rows', profile.totalRows === 6);
    assert('1.4 Duplicate rows detected', profile.duplicateRowCount === 1);
    
    const nameCol = profile.columns['name'];
    assert('2.1 Empty string detected', nameCol.emptyStringCount === 1);
    assert('2.2 Whitespace string detected', nameCol.whitespaceCount === 1);
    assert('2.3 Missing values combine null + empty + whitespace', nameCol.missingCount === 2);

    const scoreCol = profile.columns['score'];
    assert('3.1 Null score detected', scoreCol.nullCount === 1);
    assert('3.2 Negative count detected', scoreCol.negativeCount === 1);
    assert('3.3 Outlier detected', scoreCol.outlierCount! > 0); // 1000 is an outlier

    const regCol = profile.columns['registered'];
    assert('4.1 Invalid date detected', regCol.invalidDateCount === 1);
    assert('4.2 Future date detected', regCol.futureDateCount === 1);

    const idCol = profile.columns['id'];
    assert('5.1 Type inconsistency detected (text in int field)', idCol.typeConsistencyPercentage! < 100);

    assert('6.1 Issues list generated', profile.issues!.length > 0);
    assert('6.2 Critical issue generated for dates', profile.issues!.some(i => i.severity === 'Critical' && i.issue.includes('date')));

  } catch (err: any) {
    assert('Data Quality tests execution', false, err.message);
  }

  return results;
}
